### PR TITLE
Added switch and function to enable auto sync of existing MySQL users to ProxySQL

### PR DESCRIPTION
**Pull request by alaphoid**
I find the proxysql-admin tool very handy but it does not currently handle bringing in the existing users from MySQL. Since I was adding ProxySQL to existing installations I really needed this feature and ended up scripting it separately. There are probably more people like me that would find this useful so I figured I would take a stab at adding the functionality to the proxysql-admin script for all to use.

This replaces PR #48

### CODE REVIEW

**Comment by rameshvs02** [comment]
Hi

I have included your PR with some modification in v1.3.7-dev branch. Could you please check it ?
https://github.com/percona/proxysql-admin-tool/commit/5f7d400e514e6c038604c6cd582fa8218b1d7bc2

**Comment by alaphoid** [comment]
Looks perfect, thanks.

**Comment by rameshvs02** [comment]
Hi @alaphoid 

Why do we filter `pxc_` users from mysql user list ? Any specific reason for it ?

**Comment by alaphoid** [comment]
Mostly because the script creates an application user whether I wanted it or not, in my case I didn't want nor need it so I just filtered it out in my user sync script that I later merged into proxysql-admin just for the purpose of the pull request.  It should probably be removed from the filter, and I think it would be nice if creation of the application user was optional.  And if it is already optional then just forget I said anything about it and remove the filter :)

**Comment by rameshvs02** [comment]
Okay, I am removing that user from filter list.
Re: making application user creation optional, I will look into it.

**Pull request closed without merging**
