### PR TITLE
Added a switch and function to enable auto sync of existing MySQL users to ProxySQL.

### PR DESCRIPTION
**Pull request by alaphoid**
I find the proxysql-admin tool very handy but it does not currently handle bringing in the existing users from MySQL.  Since I was adding ProxySQL to existing installations I really needed this feature and ended up scripting it separately.  There are probably more people like me that would find this useful so I figured I would take a stab at adding the functionality to the proxysql-admin script for all to use.

### CODE REVIEW

**Comment by rameshvs02** [comment]
Thank you very much for the PR :) 

Current patch only support PXC-5.7 version. I will modify the patch to support with PXC-5.6 version and merge the changes in next release.

**Comment by rameshvs02** [comment]
Yes, password column has been removed from user table in 5.7 release.

**Comment by dbpercona** [comment]
This looks like a very nice feature!   We are in the process of add automated unit testing to proxysql-admin.sh.   I would like to add a test for this feature before merging the code.  alaphoid,  can we notify you when we have added the unit test suite?

**Comment by alaphoid** [comment]
You bet, thanks.

**Comment by alaphoid** [comment]
I added support for both 5.6/5.7 in my master not realizing it would take effect here, so I guess its part of this pull now.  I'm just figuring out github :)

**Comment by alaphoid** [comment]
Closing this pull request to open a new one based off a branch in my fork rather than master.

**Pull request closed without merging**
